version: '2.7'

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: zoomin
    restart: on-failure
    ports:
    - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zoomin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

